WORKING ON PAGE NOT FOUND
RichardTsibu76/AirBnB_clone_v3 pull request #2
Opened 2024-04-26 13:28 UTC by RichardTsibu76

Please you may review some changes on task five the page now 
T
 CORS extension is used to enable Cross-Origin Resource Sharing (CORS) support. CORS is a mechanism that allows web servers to specify who can access their resources on a different domain.

2024-04-26 18:25 UTC, nanafox requested changes

2024-04-26 18:25 UTC, nanafox commented on api/v1/app.py
Could you please add the function docstrings?
Also, could you confirm your imports? I don't see some of the things you've imported.

2024-04-26 18:25 UTC, nanafox commented on api/v1/app.py
I would suggest that you start from task 3 instead since it's where everything
gets defined. This way, you will have a consistent flow as you tackle the tasks
that follow, like this task for example.

2024-04-27 00:38 UTC, nanafox commented on api/v1/app.py
I've modified this file to answer task 3 instead. I've added the initial
`/status` route to check to ensure that our is up before proceeding with
anything else. From here, we can continue to improve on the API and add other
endpoints. Also, I refactored some of the previous codes so it's shorter and a
bit more *Pythonic*.

2024-04-27 00:46 UTC, nanafox approved these changes
I have updated the code solve task 3 instead which is meant to set things up for the API. I have also tested and verified that it's working from my end. 

You can do same at your end and provide feedback. Here's the command to use:

`HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db HBNB_TYPE_STORAGE=db HBNB_API_HOST=0.0.0.0 HBNB_API_PORT=5000 python3 -m api.v1.app`

2024-04-27 00:52 UTC, merged

2024-04-27 05:03 UTC, RichardTsibu76 commented
Alrght that is well mentioned , i will look into into it again and see 
Thank you very much Sir